apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinatra-app-1
  template:
    metadata:
      labels:
        app: sinatra-app-1
    spec:
      containers:
      - name: sinatra-app-1
        image: st3el/app:v5


