apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinatra-app
  template:
    metadata:
      labels:
        app: sinatra-app
    spec:
      containers:
      - name: sinatra-app
        image: st3el/app:v5

